a = input("Digite algo: ")
print("O tipo primitivo é: ", type(a))
print("Só tem espaços? ", a.isspace())
print("É um número ? ", a.isnumeric())
print("É alfabético ? ", a.isalpha())
print("É alfanumérico ? ", a.isalnum())
print("É maiúscula ? ", a.isupper())
print("É minúscula ?", a.islower())
print("Está capitalizado ? ", a.istitle())
